### ISSUE TITLE
Create demographics dataset and blog post for it  

### ISSUE THREAD

**Issue by zelima** [datahubio/datahub-v2-pm#102]
We're publishing `population-growth-estimates-and-projections` dataset from United Nations Population Division. It is in `xlsx` format and available at https://esa.un.org/unpd/wpp/DVD/Files/1_Indicators%20(Standard)/EXCEL_FILES/1_Population/WPP2017_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES.xlsx

Goals:
* Prepare an Article about Demographic Datasets. 
* use/create a dataset for this article
* write down blockers/issues
* We want to have automated behaviour that gets the excel file from the URL, processes it and updates on DataHub website.

## Acceptance criteria 

* [x] issues are identified and reported 
* [x] article exists in hackmd.
* [x] dataset exists on datahub https://datahub.io/zelima/population-growth-estimates-and-projections

## Tasks

* [x] Identify datasets for your story
  * [x] What datasets do you need - add these to awesome as an exercise
* [x] Publish them <-- main task
  * [x] Bonus points for automation
* [x] Embed tables / graphs / links in your blog posts (not possible really atm (?))
* [x] Record bugs / blockers as you do this

## Analysis 

```
data cat https://esa.un.org/unpd/wpp/DVD/Files/1_Indicators%20(Standard)/EXCEL_FILES/1_Population/WPP2017_POP_F01_1_TOTAL_POPULATION_BOTH_SEXES.xlsx | less
```

* above does not allow to see different sheets - would be useful 
* above command fails with `syntax error near unexpected token ('`

* Sometimes pipelines fails and no error message or reason is displayed on showcase
  * no error message is displayed if validation pipeline fails.
  * Debugged: Headers in flow.yaml must be strings not integers when un-pivoting Eg
    * Wrong: `headers: [country,2001,2002]`
    * Correct: `headers: [country,"2001","2002"]`
* Slight typo in resource name in flow.spec leads to unrelated error message. 
  * did not pass skip_row parameters appropriately an validation fails as there are Eg blank row
  * Pipeline failed with header lengths not matching number of fields in source. While this was not a case
    * had to check pipelines
    * had to check source API for logs
    * And finally by accident discovered typo
* I had to write another script to construct dp.json for automation. and it's ~4000 lines long. 
  * Hard to debug when something goes wrong
  * Why do we need to write a script? data-cli should generate that?
  * why push-flow needs everything to be remote? why not push to raw score?
* Not able to plot line from multiple resources in one graph. (though in views one can define multiple resources.)
* really bad User experience when working with views and big datasets
  * You have to re-process ~50 MB of data on every little change with views and wait for ~10 mins
    * 10 mins might also be related to loading from a remote resource (i.e. Github raw content).
  * Local preview of graphs would be great here
  * Can we show the views/preview online while data is still processing?

**Comment by zelima** [comment]
FIXED
