### ISSUE TITLE
[Epic] Datahub QA tests

### ISSUE THREAD

**Issue by zelima** [datahubio/datahub-v2-pm#109]
As an admin, I want to have test spec written and executed twice by different people so that I know where I'm good or where I should improve.

As an admin, I want to monitor test outcome, so that I know the quality of the product is improving or no.

As a product owner, I want to test the product under predefined criteria (spec), so that showcase page is perfected and we have a perfect data push flow that only has minor bugs - the product is attractive to users!

## Acceptance Criteria

* [x] test spec covers the most of possible scenarios and is documented in spreadsheet
* [x] tests are executed regularly (daily) by responsible person(s)
* [x] Outcome of the tests is written in spreadsheet

## Tasks

* [x]  come up with specs and fill the spreadsheet - https://docs.google.com/spreadsheets/d/1ssAH2LmHMWyc38H6I85GP9OZLcJOK0klw-RZmKuEpZk/edit#gid=0
* [x] decide eabout example packages to use from https://github.com/frictionlessdata/test-data
  * [x] identify what's missing and add if necessary 
* Implement tests - automate as much test cases as possible (moved to #120 )
* [x] follow basic loop and report outcome in spreadsheet

## analysis 

**Basic loop that should be good for the launch** (can be used in the sign up process):

* Install data command line tool
* *data get sample-data (Or use your own data) [not a focus]*
* data push
  * (init behind the scenes will add a graph for them)
* Visit the showcase page
  * My data appears quickly
    * I.e. Instantaneously after cli says it’s published
  * Tweet the result ;-) with a good title (e.g. 'US GDP - datahub.io')
    * Bonus: "twitter cards" / facebook cards
  * Get the JSON … 
  * Validation report
* Can use the data
  * in my code
  * data get xxx

**Comment by zelima** [comment]
@AcckiyGerman think we can close this one, WDYT?

**Comment by AcckiyGerman** [comment]
@zelima yes, the issues pipeline is working now.

**Comment by AcckiyGerman** [comment]
Status:
- all key user scenarios are working and covered by tests
- advanced user scenarios are covered by tests (not all scenarios are working yet, but we have documented bugs and we are actively fixing this issues)
- test-data is created

Not ready:
- [ ] automate as much tests as possible

@zelima @anuveyatsu Automating tests are important. I suppose to create separate issue for tracking its progress, so we could close this EPIC

**Comment by zelima** [comment]
@AcckiyGerman +1

**Comment by anuveyatsu** [comment]
@AcckiyGerman @zelima I've opened a new issue for automation of these tests #120 so closing this one.
