### ISSUE TITLE
Get traffic on old related sites and update redirect plan

### ISSUE THREAD

**Issue by rufuspollock** [datahubio/datahub-v2-pm#11]
As Product Owner I want to get traffic stats from old datahub.io and data.okfn.org so that I can understand what people are looking for

As Product Owner I want to get traffic stats from old datahub.io and data.okfn.org so that I can redirect traffic on new datahub.io to maximize usage on the new site

## Acceptance criteria

* [x] A plan of redirects for old urls to go within new datahub.io rather than just off to old.datahub.io as we do currently
  * [x] datasets
  * [x] resources
  * [x] tags (?)

## Tasks

* [x] Download top XXX accessed pages (probably 2500 for datahub.io but maybe not) and put in [traffic analysis spreadsheet][]
  * [x] Download top 2500 for thedatahub.org (old.datahub.io) - last 2y
  * [x] Download top 2500 for data.okfn.org - last 2y
* [x] Use this information to inform redirect plans
  * [x] Identify which, if any, match core datasets we have in new site (so that we can redirect)
    * [x] data.okfn.org - only check those with traffic above 500 and which are not core (because core we know how to redirect)
    * [x] old datahub.io
  * [x] Identify any datasets we don't currently have but we could / should have
* [x] Get the traffic sources

[traffic analysis spreadsheet]: please-ask

**Comment by Mikanebu** [comment]
FIXED, analysis done in hack.md `my daily plan`
