### ISSUE TITLE
[Epic] QA tracker with relevant severity

### ISSUE THREAD

**Issue by zelima** [datahubio/datahub-v2-pm#113]
We need to categorize bugs and track them in the best way. 

## Acceptance Criteria

- [x] bugs are categorized and each has it's own Epic with issues inside 

## Tasks

- [x] Write user stories fo this 
- [x] create EPIC for each bug category (cli, frontend, etc)
    - Installation https://github.com/datahq/datahub-qa/issues/48
    - Data Push https://github.com/datahq/datahub-qa/issues/47
    - Data Get https://github.com/datahq/datahub-qa/issues/45
    - Using data in programming languages https://github.com/datahq/pm/issues/116
    - Frontend https://github.com/datahq/pm/issues/112
    - Push speed https://github.com/datahq/pm/issues/111
    - QA Tests https://github.com/datahq/pm/issues/109
## Analysis 

Existing bugs:

- if i search "united nations" it shows me results for "united states" - probably due to scoring algorithms
- johnsnowlabs result is higher than core - core should happen first

**Comment by AcckiyGerman** [comment]
`data get` epic: https://github.com/datahq/datahub-qa/issues/45

**Comment by AcckiyGerman** [comment]
FIXED: 
https://github.com/datahq/datahub-qa/issues#boards
![image](https://user-images.githubusercontent.com/11707682/35691493-4098b13a-0781-11e8-89e5-699a43ef722a.png)

QA tracker were created, majority of the bugs are categorized, instructions for staff are created in the hackmd (bug-flow will be shown on the standup).
