### ISSUE TITLE
data.okfn.org redirects to datahub.io

### ISSUE THREAD

**Issue by rufuspollock** [datahubio/datahub-v2-pm#12]
As Site Admin I want to redirect data.okfn.org to datahub.io so that users get a higher quality experience and we increase our traffic

## Acceptance criteria

* [x] data.okfn.org redirects to datahub.io with no breakages

## Tasks

* [x] Research the redirects we need to put in place
  * Check heroku logs ...
  * Check site
  * Read code
* [x] Update [redirect plan]
* [x] Implement these redirects in the data.okfn.org code
  * We have to put them there because we can only do bulk redirect /* => / on dnsmadeeasy (which is what manage)
* [x] Test this by hand

[redirect plan]: https://docs.google.com/a/datopian.com/spreadsheets/d/1wI82wn_-dHzmbZ-KtmiNB0l1GtxEzaHXDjCQtSsEvOg/edit?usp=drive_web

**Comment by anuveyatsu** [comment]
FIXED. Implemented following redirects:

* `data.okfn.org` => `datahub.io`
* `data.okfn.org/data/core*` => `datahub.io/core*`
* `data.okfn.org/data/datasets*` => `datahub.io/core*`
* `data.okfn.org/data/{owner}*` => `datahub.io`
* `data.okfn.org/tools*` => `datahub.io`
* `data.okfn.org/roadmap*` => `datahub.io/docs`
* `data.okfn.org/standards*` => `datahub.io/docs/data-packages`
