### ISSUE TITLE
[Epic] Automate QA tests

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#120]
As an admin, I want QA tests to be automated so I don't need to run them manually each time.

We want to automate as much as possible of QA tests.

## Tasks

- [x] cli tests - https://github.com/datahq/data-cli/issues/288
- [x] push related tests - https://github.com/datahq/data-cli/issues/291 and https://github.com/datahq/data-cli/issues/289
- [x] user rights & restrictions - https://github.com/datahq/data-cli/issues/297
- [x] get command related tests -

**Comment by Mikanebu** [comment]
get command related tests => https://github.com/datahq/data-cli/issues/299

**Comment by zelima** [comment]
FIXED
