### ISSUE TITLE
Analyse traffic data

### ISSUE THREAD

**Issue by rufuspollock** [datahubio/datahub-v2-pm#14]
Use behaviour and source data (from #11) to work out how we can better support what users are looking for and what features we need

## Acceptance criteria

* [x] A summary of what we think people are looking for
  * [x] what google searches are they doing, what datasets are popular, what are related searches so that we can design our new site well

## Tasks

* [x] Research on how to use google analytics to answer these questions (?)
* [x] Come with a list of questions to ask? E.g. what else are people searching for, where do they come from? are they on mobile (do we need good mobile support)? etc
* [x] Write a report (in gdoc, hackmd etc) 
  * report is located in my daily plan hack.md

## Analysis for last 2 years

Come with a list of questions to ask?  There are several main questions we can get an answer.

- How your users are finding your site? If we take a look at acquisition overview, we can see the chart of how many users found our website. 

These following questions can be answered from the `behaviour insights` 

- How long your users tend to stay on your site?
- Which pages of your site are the most valuable or popular to your visitors?
- Where your website traffic comes from?
- How people coming from different social networks?
- What’s the intent of visitors who come to the page?
- Is our website working effectively?
- Average page load?
- What type of devices connected to website? 
- What kind of browsers are used?
- What is the location of the users?
- What kind of languages are popular?
- Which social media channels give the most traffic?

**Comment by Mikanebu** [comment]
FIXED, analysis written in Google Spreadsheet in my hack.md `daily plan`
