### ISSUE TITLE
DataHub Payments

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#147]
User Story:
* As a user, i want a payment interface on datahub, so that i can pay for data requests, or other services.
* As an admin, i want a payment interface on datahub, so that i can charge customers for the data requests.

## Acceptance criteria

* [x] I'm able to charge a given customer for some exact amount

## Tasks

* [x] Get a clear idea of requirements
* [x] Initial look at the stripe API for NodeJS
* [x] Formulate a plan for how the process of payments would be implemented
* [x] Create test API key for stripe
* [x] Implement it and test
* [x] Deploy

## Analysis

As the first step we want to implement a basic payment process, e.g., we want to be able to charge a given customer for some exact amount. For instance, a user requested data and we want to charge him for 10 USD so we can send a link for the invoice.

References:
https://stripe.com/docs/quickstart
https://stripe.com/docs/api/node

Example logic and URIs:
https://datahub.io/pay - this opens a blank form where you can create a payment adding amount + description + customer
https://datahub.io/pay?id=xxx
https://datahub.io/pay?success=true  or https://datahub.io./pay?failure=true for the response
