### ISSUE TITLE
[Epic] Front page and offers pages redesigned and with clear hypothesis tests (A/B) built in

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#150]
From the sprint plan:

* [x] Front page and offers pages redesigned and with clear hypothesis tests (A/B) built in
  * [x] Design and review home page https://github.com/datahq/frontend/issues/267
  * [x] Implement home page https://github.com/datahq/frontend/issues/268
  * [x] Design and review offer pages (consultancy, data-os) https://github.com/datahq/frontend/issues/271 and https://github.com/datahq/frontend/issues/272
  * [x] Implement offer pages
    * [x] /consulting page - https://github.com/datahq/frontend/issues/273
    * [x] move data-os offer to /data-os/  - https://github.com/datahq/frontend/issues/274
  * [x] Experiments [~1d]
    * [x] Raise a few hypotheses to test (+and experiments) https://github.com/datahq/frontend/issues/269
    * [x] Choose 1-2 and implement https://github.com/datahq/frontend/issues/270
  * [x] integrate with kpis after implementation https://github.com/datahq/datahub-kpis/issues/12

**Comment by anuveyatsu** [comment]
FIXED
