### ISSUE TITLE
[Epic] Showcase page optimization

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#156]
## Tasks

* [x] check the current state, eg, interaction percentage, bounce rate [1h]
* [x] track missing events if there is any [3h]
* [x] UX review and define hypotheses for experiments - https://github.com/datahq/frontend/issues/283
* [x] implement A/B tests - https://github.com/datahq/frontend/issues/284

## Analysis

State on 26 May 2018 - before starting experiments (average for the last 6 weeks):

Average time on the page: 00:02:44
Bounce rate: 36.33%
Exit: 60.23%
Downloads (r links clicks): 1949.5 clicks (weekly average from 1st April to 26 May)

Interaction (6 May - 26 May 2018):

Scrolling the page:
  * not scrolled: 23.73%
  * scrolled 25% of the page: 22.85%
  * scrolled 50% of the page: 20.22%
  * scrolled 75% of the page: 17.63%
  * scrolled 100% of the page: 15.57%

**Comment by anuveyatsu** [comment]
FIXED
