### ISSUE TITLE
Send first newsletter 

### ISSUE THREAD

**Issue by zelima** [datahubio/datahub-v2-pm#162]
As project Manager I want to email about updates re datahub.io in the first quarter of 2018, so that my users are aware of what we've been up to

## Acceptance Criteria

* [x] newsletter is sent to all of our customers
* [x] Email itself is not over-complicated, if necessary use https://datahub.io/blog/q1-2018-review for complete review 

## Tasks

* [x] Write the letter @Branko-Dj 
* [x] Review and send @tanvirchahal @zelima
* [x] send

**Comment by Branko-Dj** [comment]
First draft of the newsletter https://hackmd.io/uxDTjbYsQOyU_lA0cGqppA

**Comment by zelima** [comment]
FIXED
