### ISSUE TITLE
[Epic] Awesome pages - 18 June 2018

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#166]
## Tasks

* [x] create "economic data" section - https://github.com/datahq/awesome-data/issues/24
* [x] review existing awesome pages if the links are working
  * [ ] Probably better to have local links (/core/vix) instead of absolute links
* [x] Awesome pages ramp-up - https://github.com/datahq/pm/issues/167

**Comment by anuveyatsu** [comment]
Closing as FIXED and removing creating logos/icons for awesome pages from this epic.
