### ISSUE TITLE
[Epic] Awesome pages ramp-up

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#167]
As a Developer, I want to have "awesome" pages per subject so we can promote our existing "core" datasets on the web.

As a User, I want to be able to find datasets by theme via search engines so I can arrive at datahub and find all I need in one place.

## Acceptance criteria

* [x] existing core datasets are analysed and have a "theme", e.g., "gdp" is "economy"
* [x] there is a page per each theme at `/awesome/...`
* [ ] awesome pages have new design

## Tasks

* [x] One awesome page per subject - https://github.com/datahq/awesome-data/issues/25
* [x] Proper links to prominent datasets (indexable!)
* [ ] New design
  * [ ] mockup - https://github.com/datahq/frontend/issues/292
  * [ ] implementation - https://github.com/datahq/frontend/issues/293
* [x] Blog post - https://github.com/datahq/pm/issues/168

**Comment by anuveyatsu** [comment]
Closing as FIXED as we have decided to not implement a new design for the awesome pages due to lack of evidence for its need.
