### ISSUE TITLE
Data Factory free offer marketed [part 1]

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#180]
As the DataHub team, we want to market our Data OS offer so that people from the community and our mail list aware of the product and can get in touch in case this is what they're interested in.

## Acceptance criteria

* [x] Mailchimp template is ready
* [x] Offer content approved by Adam/Rufus

## Tasks

* [x] Prepare offer Email on MailChimp
* [x] Write offer
* [x] Talk about this and ask for feedback on the datahubio/chat + email Paul and Jo

**Comment by anuveyatsu** [comment]
FIXED - template is ready on mailchimp
