### ISSUE TITLE
Copy interesting datasets from old datahub [part 1]

### ISSUE THREAD

**Issue by Branko-Dj** [datahubio/datahub-v2-pm#183]
Take a look at old.datahub.io/dataset and copy interesting datasets from it with their tags. Use dataflows for this scrape. The current status of the analysis can be found in our DataHub Analysis document under title **Copy over popular datasets from old datahub**

## Acceptance criteria

* [x] we have a list of datasets that we are going to copy to new datahub
* [x] analysis for scraping and publishing is done

## Tasks

- [x] Decide which datasets would be interesting to have on the new platform
  - [x] discuss with @anuveyatsu about popular datasets using search console
  - [x] create a list of links for datasets to be scraped
- [x] conduct preparation work, eg, email opencorporates for license/permission

**Comment by anuveyatsu** [comment]
FIXED - we're going to copy/redirect following datasets:
1. global airports (already done in this issue)
2. Tennis data
3. open corporates
4. yago
5. dblp
