### ISSUE TITLE
[Marketing] Analyze survey results

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#186]
As the DataHub team, we want to know what our users have said in our survey so we can identify what should we improve.

## Acceptance criteria

* [x] written analysis of survey results
* [x] list of users who are happy to be contacted and participate in the datahub improvement

## Tasks

* [x] analyze responses
* [x] create priority list of emails
* [x] draft an email
* [x] prepare a new revised survey

**Comment by anuveyatsu** [comment]
FIXED see details in the spreadseet
