### ISSUE TITLE
New users survey is live

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#191]
As a Datahub team, we want to have improved version of the survey so it is easier to fill in the form for users and analyse for the team.

## Acceptance criteria

- [x] Survey is modified to ease stats collection with multiple choice questions

## Tasks

- [x] Create multiple choice questions for most of the survey questions
  - [x] when selecting multiple choices take a look at responses we have
  - [x] create a new form (don't modify old one as it can mess up responses spreadsheet)
- [x] add new questions if necessary
- [x] Connect new survey to our website and google spreadsheet

## Analysis

We want to:

* improve the survey by using previous responses - convert free-form questions to multiple choice or checkboxes so it's easier to respond + analyze later
* ask about what data users are interested in so we can have a sense about what to prepare
* make the form smarter, eg, if user is interested in publishing then don't ask about finding data

**Comment by anuveyatsu** [comment]
FIXED
