### ISSUE TITLE
Implement old datahub.io redirects

### ISSUE THREAD

**Issue by rufuspollock** [datahubio/datahub-v2-pm#20]
As an Admin I want to implement the internal redirects so that people get best experience by finding high quality datasets on datahub.io

This is follow up to #11 

## Acceptance criteria

* [x] All selected "old" datahub.io items redirect inside new datahub.io (that does not require creating new datasets in the new datahubio)
* [x] All non-selected datahub.io items (most of them) still redirect nicely to old.datahub.io

## Tasks

* [x] Make a list of redirects in a spreadsheet
  * [x] Those we can make straight away
  * [x] Those that require datasets to be created (or "awesome" pages to be created")
  * [x] Make a list of datasets / packages we need to create
* [x] Implement the immediate redirects (TODO: do we want to hard code or run off a list we import at startup?)
* [ ] Create new datasets needed
* [ ] Implement these redirects

Estimate: my guess is prep is ~1h, immediate redirects work is ~2-3h (if we make it extensible) and migrating datasets is ~8h.

**Comment by zelima** [comment]
@Mikanebu where are we on this task? Think part of this is implemented right? Could you please update

**Comment by anuveyatsu** [comment]
All redirects that don't require creating new datasets are now implemented here - https://github.com/datahq/frontend/commit/0e01b9f16850fd99e9c113c6c2b54a6c4399727e

**Comment by anuveyatsu** [comment]
Closing this issue as FIXED and moving leftovers to the new issue here - https://github.com/datahq/pm/issues/62
