### ISSUE TITLE
[EPIC] Data Requests - 16 Jul 2018

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#200]
## Tasks

* [x] improve the existing data requests form
* [x] automate data collection, eg, form to CSV
* [x] analyze previous results

**Comment by anuveyatsu** [comment]
FIXED
