### ISSUE TITLE
Analyze data requests

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#201]
As the DataHub team, we want to conduct an analysis of received data requests so that we can find patterns about users need.

## Acceptance criteria

* [x] we have a CSV of all requests
* [x] we have a list of fields (eg financial) by popularity

## Tasks 

- [x] Compile and calculate requests popularity by category

**Comment by Branko-Dj** [comment]
FIXED. The analysis was done from old google forms and formspree. The analysis is outlined in a spreadsheet named Data requests analysis
