### ISSUE TITLE
Improve data requests form

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#202]
As the DataHub team, we want to make improvements into the data requests form so that we collect more accurate data and can improve our performance when processing a request.

## Acceptance criteria

* [x] the form has more relevant fields, e.g., we request users name, background

## Tasks

* [x] @Branko-Dj to brainstorm and provide necessary fields
* [x] @tanvirchahal to implement the changes
* [x] @tanvirchahal make sure 'replyto' and 'subject' fields configured in a useful way (i.e. reply to is email of person submitting, subject is something useful e.g. "Contact request from {name}") so that when these submissions arrive in our ticketing system they don't just all say "Form submission from FormSpree" - see https://www.raymondcamden.com/2016/01/22/dynamic-subjects-with-formspree for how to do this (can you start with Open Revolution)

**Comment by anuveyatsu** [comment]
FIXED - we've decided to replace the form with Google forms so we can collect more insights + it's easier to analyse later. We have implemented a script (as an google script) that creates a ticket in the freshdesk by sending email to support@datahub.io
