### ISSUE TITLE
Automate data collection for Data Requests

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#203]
As the Datahub team, we want to automate data collection of data requests submission so we can easily analyse what our users want.

## Acceptance criteria

* [x] form submissions are stored as CSV

## Tasks

* [x] analyse what we can do with formspree / freshdesk
* [x] consider formspree alternatives that provide Form to CSV feature
* [x] implement a solution
* [x] deploy

**Comment by anuveyatsu** [comment]
FIXED will be in production with the next deployment
