### ISSUE TITLE
Data Factory free offer marketed [part 2]

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#213]
As the DataHub team, we want to market our Data OS offer so that people from the community and our mail list aware of the product and can get in touch in case this is what they're interested in.

## Acceptance criteria

* [ ] Email scheduled to mass subscribers list
* [ ] Blogpost added and published

## Tasks

* [ ] Send to subscribers
* [ ] DataOS Offer blogpost
