### ISSUE TITLE
[EPIC] Regional datasets

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#219]
As a User, I want to have comprehensive regional/logistical datasets so that I can use it in my applications.

## Tasks

* [x] country table with ISO alpha2 code, country name in CLDR, english country name and continental code + currency details, capitals, date formats, development status, dialing codes,DST info, membership in EU, NAFTA and NATO, various region codes, postal code formats, top level domains, unit of measures and work week patterns
* [x] language codes table
* [x] locales table
* [x] timezones table
* [x] DST information table
* [x] holidays table

**Comment by anuveyatsu** [comment]
FIXED
