### ISSUE TITLE
Comprehensive country table

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#220]
As a User, I want to have a comprehensive country table that have information about country names, codes, currency, regions, dialing formats and other logictics related information so that I can reference it and use it in my application.

## Acceptance criteria

* [x] all required columns are collected, scraped and automated
* [x] SQL tables are generated

## Tasks

* [x] check missing and invalid columns and improve them
* [x] automate generation of tables
* [x] auto generate SQL tables

**Comment by anuveyatsu** [comment]
FIXED - refer to our internal docs for more details
