### ISSUE TITLE
Language codes table

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#221]
As a User, I want to have languages table with their alpha2, alpha3 and names mapped to country codes so that I can use it in my application.

## Acceptance criteria

* [x] all required columns are generated
* [x] scraping is automated via datahub
* [x] SQL tables are generated

## Tasks

* [x] check source data and setup automation via Travis to datahub
* [x] fetch required data into CSV
* [x] generate SQL tables

**Comment by anuveyatsu** [comment]
FIXED - see our internal docs for more details
