### ISSUE TITLE
Timezones table

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#224]
As a User, I want to have timezones table with their UTC offsets, UTS offsets in DST and names mapped to country codes so that I can use it in my application.

## Acceptance criteria

* [x] all required columns are generated
* [x] scraping is automated via datahub
* [x] SQL tables are generated

## Tasks

* [x] fetch required data into CSV
* [x] generate SQL tables

**Comment by anuveyatsu** [comment]
FIXED - see our internal docs for more details
