### ISSUE TITLE
DST table

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#225]
As a User, I want to have DST table with their start and end dates mapped to country codes so that I can use it in my application.

## Acceptance criteria

* [x] all required columns are generated
* [x] SQL tables are generated

## Tasks

* [x] fetch required data into CSV
* [x] generate SQL tables

**Comment by anuveyatsu** [comment]
FIXED - see our internal docs for more details
