### ISSUE TITLE
Holidays table

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#226]
As a User, I want to have holidays table with their names, types and dates mapped to country codes so that I can use it in my application.

## Acceptance criteria

* [x] all required columns are generated
* [x] auto scraping is setup
* [x] SQL tables are generated

## Tasks

* [x] fetch required data into CSV
* [x] generate SQL tables

**Comment by anuveyatsu** [comment]
FIXED - see our internal docs for more details
