### ISSUE TITLE
[EPIC] Regional datasets - 13 August

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#228]
## Tasks

* [x] answer the questions [1h]
* [x] work on additional CLDR data - https://github.com/datahq/pm/issues/229
* [x] create many-to-many relationships - https://github.com/datahq/pm/issues/230
* [x] work on currency symbol data - https://github.com/datahq/pm/issues/231
* [x] work on dialing prefix data - https://github.com/datahq/pm/issues/232
* [ ] work on postal zip code lenght data
* [ ] work on length of phone numbers from Country_Dialing_Prefix, Country_Calling_Code and Phone_Number_Format_Type
* [x] scrape territory subdivisions

**Comment by anuveyatsu** [comment]
Closing this as FIXED as we have completed the required items here. The optional items will remain until the client's request.
