### ISSUE TITLE
Trial automation of core data scraping

### ISSUE THREAD

**Issue by zelima** [datahubio/datahub-v2-pm#24]
As a Publisher I want to have my dataset updated [automatically] regularly for me so I do not need to update them manually and it is up to date

* Source data: remote url (not on my machine)
* May be some cleaning needed e.g. removing rows, fixing up dates
* Need to be able to set the regularity of rechecking the source data for changes (cronnability)
* Only use the features that pipelines (and tabulator) already have

core datasets analysis spreadsheet: 
https://docs.google.com/spreadsheets/d/14kJluhePaMOx6vYBic0poVjDYK3I8-v_xF3sv4Focac/edit#gid=405792816

## Acceptance Criteria

* [x] Dataset X,Y is published on datahub.io once and is uptodate daily/monthly/... without re pushing it.

## Tasks

* [x] Add script link
  * [x] (On simple items) Improve script summary to list major steps
    * [x] add any operation types we have not yet covered to the new sheet that list operation types and think whether we could support in DPP
  * [x] Fill in column DPP OK
* [x] choose 2-3 core datasets to work on based on a) DPP OK b) interest / popularity c) regularity of updating (daily is better!)
  * finance-vix
  * bond-yields-us-10y
* [x] For each of them summarize what you would do to have them work in DPP
* [x] Proceed to implement
* [x] Add `data push flow` command into core datasets tools (0.5)

# Analysis

In current github datasets we have:

* Instructions for cleaning: scripts, cached data etc
* Cleaned version: datapackage.json + clean data

Going forward have:

* Instructions for cleaning: pipeline instructions (see below)
* Cleaned version: datahub (maybe we will find a way to loop this back to github but not sure we need it ...)

New github has:

```
.datahub/
  datapackage.json
  flow.yml
```

.datahub stuff ...

```javascript=
// datapackage.json
{
  title: "..." // copy from clean datapackage.json
  "resources": [
    {
      "path": "http://www.cboe.com/publish/ScheduledTask/MktData/datahouse/vixcurrent.csv"
     "schema": {
        "fields": [
           {
             "name": "Date",
             "type": "date",
             "format": "d/m/yyyy"
            }
         ]
      }
    }
  ]
}
                
// flow-template.yml
meta:
  findability: <published/unlisted/private>
inputs:
  -
    tabulator:
      skipRows: 1
      // rowTransform: "function(row) { row[0] = row[0].replace('_', '-')}"


TODO: What about local caching ...
  * How do we update "derived" datahub datapackage.json with this - do we point to original or ...?
```

Update data push so that we can merge flow templates with source.yml

### define metadata in yaml

* bond-yields-us-10y
  * remove first 6 rows(including header row)
  * add new header row(Date, Rate)
  * regularity is MONTHLY
```
processing:
  -
    input: monthly
    tabulator:
      skip_rows: 6
      headers:
        - Date
        - Rate
    output: monthly
    schedule:
        crontab: '* * * 1 *'


```

* finance fix 
  * remove first 2 rows(including header row)
  * add new header row(Date, VIXOpen, VIXHigh, VIXLow, VIXClose)
  * regularity: DAILY

```
processing:
  -
    input: fix-daily
    tabulator:
      skip_rows: 2
      headers:
        - Date
        - VIXOpen
        - VIXHigh
        - VIXLow
        - VIXClose
    output: vix-daily
    schedule:
        crontab: '* * 1 * *'

```

### push the metadata to assembler

TODO

**Comment by zelima** [comment]
FIXED.
three datasets are updated in auto mode for now
* https://datahub.io/core/bond-yields-uk-10y
* https://datahub.io/core/bond-yields-us-10y
* https://datahub.io/core/finance-vix

You can find script for pushing remote resources in this commit https://github.com/datahq/datahub-cli/pull/181/commits/c6285117bb3cd6afc245643fb2adc53498032d30

**Comment by zelima** [comment]
Reopening as we need small script to push  them with script

**Comment by Mikanebu** [comment]
FIXED, Added push-flow command into core-datasets-tools
