### ISSUE TITLE
Polish READMEs for datasets

### ISSUE THREAD

**Issue by zelima** [datahubio/datahub-v2-pm#256]
Some of the READMEs are outdated or not quite exact in their descriptions Eg: https://github.com/datasets/country-list says it's update while actually, it is not.

> This list is updated whenever a change to the official code list in ISO 3166-1 is effected by the ISO 3166/MA.

## Tasks 

* [x] List core datasets
* [x] Review all core datasets and their READMEs and identify if any of them needs to be updated
* [x] Cross check with https://github.com/datasets/registry/blob/master/core-list.csv
* [x] List the ones that need
* [x] Update which necessary

**Comment by Branko-Dj** [comment]
FIXED!
