### ISSUE TITLE
[Epic] Datahub scraping using dataflows

### ISSUE THREAD

**Issue by zelima** [datahubio/datahub-v2-pm#265]
As a PM I want to get top 10 datasets and scrap them using dataflows, so that we can later integrate into the system

As a PM I want to schedule processors using dpp server so that I don't have to use Travis or external platforms to do so

As a user/PM I want to get Emails in case of processors failed after certain revision, so that I know something is not working anymore

## Acceptance Criteria 

* [ ] We have 10 datasets on datahub completely scraped via our tools

## Tasks

* [x] Refactor top-10 regularly updated datasets to use dataflows instead of custom scripts (@branko-dj) [12h] #264 
* [x] Schedule the scraping inside a newly set-up dpp server (@zelima) #269 
* [x] Add feature for sending an email in case of failure #270 
* [ ] Detect patterns and generalize as necessary

**Comment by irakli** [comment]
I think you have a wrong username.

**Comment by zelima** [comment]
@irakli true. fixed, thanks.

**Comment by zelima** [comment]
FIXED
