### ISSUE TITLE
List of certified datasets

### ISSUE THREAD

**Issue by zelima** [datahubio/datahub-v2-pm#278]
As a PM, I want to have a list of the certified datasets so that I can present them for the community and they know it was checked/validated.

## Acceptance Criteria

* [x] I have a list of the certified datasets

## Tasks

* [x] create set of criteria for a certified dataset
* [x] go through core datasets and decide which ones should be in the list of certified datasets
* [x] create the list as a CSV file and push it to PM repo (or have it in other repo)

**Comment by anuveyatsu** [comment]
Certified datasets should:

* be up-to-date
* not have validation errors
* have good README
* have source/license properties
*

**Comment by anuveyatsu** [comment]
FIXED, as a first step in the implementation of `certified` datasets, we have decided to use all `core` datasets as certified. As a next step, we will apply criteria specified above for datasets under non-core datasets that are maintained by Datahub team.
