### ISSUE TITLE
Update 'certified' property for selected datasets

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#282]
As a Developer, I want to have `certified` property in metadata of a dataset so that I can use it in the frontend to display users.

This is the next step of https://github.com/datahq/pm/issues/278

## Acceptance criteria

* [x] when I fetch a metadata for a dataset, I have a `certified` property

## Tasks

* [x] update database according to list of certified datasets, see https://github.com/datahq/pm/issues/278
* [ ] sync with @tanvirchahal and test if everything is good

**Comment by anuveyatsu** [comment]
Closing as FIXED since I've described how to know if a dataset is certified above.
