### ISSUE TITLE
Fix typos in readme of example/tutorial datasets

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#29]
## Tasks

* [x] Fix embedded datapackage.json - just copy over original one from the repos
* [x] Fix typos in:
  * [x] http://datahub.io/examples/vega-views-tutorial-lines#readme
  * [x] http://datahub.io/examples/example-sample-transform-on-currency-codes#readme
  * [x] http://datahub.io/examples/transform-example-gdp-uk#readme
  * [x] http://datahub.io/examples/transform-examples-on-co2-fossil-global#readme
  * [x] http://datahub.io/examples/vega-views-tutorial-topojson#readme
  * [x] http://datahub.io/examples/simple-graph-spec#readme
  * [x] http://datahub.io/examples/vega-views-tutorial-grouping#readme
  * [x] http://datahub.io/examples/geojson-tutorial#readme
* [x] Pull changes and push example datasets to DataHub

**Comment by anuveyatsu** [comment]
@Mikanebu I have fixed typos and replaced `{{dpjson}}` variables in our example datasets. Can you please pull latest changes and push them to datahub under `examples` user?

**Comment by Mikanebu** [comment]
@anuveyatsu pulled latest changes and pushed again under `examples`

**Comment by anuveyatsu** [comment]
FIXED.
