### ISSUE TITLE
Make sure all certified datasets are fine 

### ISSUE THREAD

**Issue by zelima** [datahubio/datahub-v2-pm#290]
Some of the certified datasets have validation errors eg https://datahub.io/core/population-growth-estimates-and-projections If dataset is certified it should not have any kind of errors 

## Acceptance Criteria

* [ ] No certified dataset with errors

## Tasks

* [ ] List all certified datasets and check the status
* [ ] investigate the reason why some of  them fail
* [ ] fix if possible
  * [ ] remove form certified list if not
