### ISSUE TITLE
Core datasets broken sources

### ISSUE THREAD

**Issue by Branko-Dj** [datahubio/datahub-v2-pm#291]
Some of the core datasets have a source that is not working anymore. As a PM I want to find alternative up to date sources

## Analysis
1. **cofog**

Source for `process.py` script on line 20 `access_db_zip_url = 'http://unstats.un.org/unsd/cr/registry/regdntransfer.asp?f=186'` is broken.

## Acceptance Criteria
- [ ] We have the new source for each of the datasets where the source is broken or missing

## Tasks
- [ ] Research and replace the broken or missing sources for the following datasets
   - [ ] https://github.com/datasets/cofog
   - [ ] https://github.com/datasets/cash-surplus-deficit
   - [ ] https://github.com/datasets/cpi-us
   - [ ] https://github.com/datasets/employment-us
   - [ ] https://github.com/datasets/investor-flow-of-funds-us
   - [ ] https://github.com/datasets/population-global-historical
   - [ ] https://github.com/datasets/uk-sic-2007-condensed
   - [ ] https://github.com/datasets/unece-package-codes
   - [ ] https://github.com/datasets/unece-units-of-measure
