### ISSUE TITLE
Test all the services in the consistent way

### ISSUE THREAD

**Issue by zelima** [datahubio/datahub-v2-pm#3]
We currently have 6 repos (+ deploy) (in Python) with several different ways of running tests.

# Acceptance criteria

- [x] al 7 repos are tested with tox

# Tasks 

- [x] refactor tests for
  - [x] bitstore https://github.com/datahq/bitstore/issues/13
  - [x] metastore https://github.com/datahq/metastore/issues/3
  - [x] specstore https://github.com/datahq/specstore/issues/1
  - [ ] ~~deploy https://github.com/datahq/deploy/issues/15~~
  - [x] assembler already setup, need to test
  - [x] datapackage-pipelines-datahub already setup to test
  - [x] auth https://github.com/datahq/auth/issues/12
## Analysis

As suggested by @akariv 

If we want to be completely consistent, we should implement something similar to this: https://github.com/okfn/oki-py/blob/master/Makefile which provides the same interface, regardless of the framework of language choice.

As for Python, the good thing about tox is that it encapsulates the test runner selection and its parameters, and also makes sure that installation and requirements are properly installed (which might be an issue when running py.test on your local environment).

cc/ @rufuspollock any comments?

**Comment by rufuspollock** [comment]
@zelima whatever @akariv recommends is the way we should go.

**Comment by zelima** [comment]
FIXED
