### ISSUE TITLE
[EPIC] deploy new factory to production

### ISSUE THREAD

**Issue by zelima** [datahubio/datahub-v2-pm#58]
We are now ready to introduce new factory to production.

## Acceptance Criteria

* [x] live on ~~Tuesday 07-11-2017~~  Wednesday 08-11-2017
* [x] Fully workable - no significant bugs by Sunday evening 12-11-2017

## Tasks
* [x] @anu + @irakli Debugging the new Factory on Testing
  * [x] Data previews not showing?
  * [x] other issues #57 
* [x] @irakli (+@adam) deploy new factory to production
  * [x] Migrate data from production to testing and see that it's working
    * [x] Migrate: create dataset & dataset revisions for existing datasets in production
  * [x] Fix deployment script https://github.com/datahq/deploy/issues/36
  * [x] ----- ONLY when everything is working ok VVV
  * [x] Run migrate script on production 
  * [x] Redeploy production
  * [x] @Mikanebu Release new CLI (wednesday)

**Comment by zelima** [comment]
FIXED
