### ISSUE TITLE
Redirect docs from http://data.okfn.org/docs

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#68]
Redirect docs from http://data.okfn.org/doc/ (individually if possible - i think we used same urls …?)

Repo is here: https://github.com/okfn/data.okfn.org-new

## Acceptance criteria

* [x] All available docs from okfn site are redirected to appropriate ones at datahub.io

## Tasks

* [x] `/doc` => `datahub.io/docs`
* [x] every document from here https://github.com/okfn/data.okfn.org-new/tree/master/doc is redirected to appropriate location in datahub.io (if document does not exist on datahub.io then it is redirected to `/docs` home page)

**Comment by anuveyatsu** [comment]
Now FIXED and deployed, e.g.:

* data.okfn.org/doc => datahub.io/docs
* data.okfn.org/doc/core-data-curators => https://datahub.io/docs/core-data/curators
* data.okfn.org/doc/anything-else => https:/datahub.io/docs
