### ISSUE TITLE
[EPIC] Blog posts on common data formats (+ connection with Data Packages)

### ISSUE THREAD

**Issue by rufuspollock** [datahubio/datahub-v2-pm#73]
As a Data Wrangler / Data Scientist I come across many obscure formats such as ARFF and want to google them so i understand what they are for and whether i can use them

Task: create short tutorials various formats that is reusable as a blog post. Make sure it mentions (tabular) data packages and DataHub at the end and explain why you'd want to use them and any tools for converting to them.

* [ ] CSV (already done as tutorial - but maybe a blog post)
* [ ] JSON
* [x] ARFF - https://www.cs.waikato.ac.nz/ml/weka/arff.html
* [ ] Parquet
* [ ] Excel
* [ ] SPSS
* [ ] Stata

For each of these:

* [ ] Explanation of the format with good links
* [ ] Link to relevant tools
* [ ] Conversion to / from data packages
* [ ] Examples on DataHub that might be relevant

Random others (probably don't do for now)

* Libraries
  * MARC
  * BibJSON
  * Allegro (Rufus has written a parser!)
* ...

**Comment by rufuspollock** [comment]
@Mikanebu this is a big epic and once we've decided what to work on we'll create an issue per format. This is not urgent but doing work on ARFF might come up given the thread on frictionlessdata/chat.
