### ISSUE TITLE
publish country-list dataset on npm

### ISSUE THREAD

**Issue by Mikanebu** [datahubio/datahub-v2-pm#75]
We want to have country-list dataset on npm published.

## Acceptance criteria

* [x] `Country-list` is publised under `@datasets/country-list`

## Tasks

* [x] convert `data.csv` to `data.json`
* [x] add script with methods like:
  * `getName` - returns name of the country
  * `getCode` - returns code of the country
  * `getNames` - returns list of names of all countries
  * `getCodes` - returns list of codes of all countries
  * `getNameList` - returns key-value object of all countries using the name as key
  * `getCodeList` -  returns key-value object of all countries using the code as key
* [x] configure `package.json`
* [x] publish on npm under `@datasets/country-list`

**Comment by AcckiyGerman** [comment]
@Mikanebu I've have installed @mikanebu/country-list via npm and test it - all works as it should be and I think it is ready for production.
Now we could connect with the guy, who created the original country-list
BUT! mention that @rufuspollock said: "but can we make sure we do that skillfully - i'd draft the text first and have someone check it before we post "

**Comment by Mikanebu** [comment]
FIXED, `country-list` is available on npm as `@datasets/country-list` https://www.npmjs.com/package/@datasets/country-list. Changes pushed on `npm` branch, Please, see https://github.com/datasets/country-list/tree/npm
