### ISSUE TITLE
Awesome pages and datasets

### ISSUE THREAD

**Issue by anuveyatsu** [datahubio/datahub-v2-pm#77]
*I found this awesome dataset (sharing), it would be awesome to have (= requests ...), here are these awesome datasets on climate change (curated topics)*

## User story

As a data wrangler I want to look at a whole set of datasets (rather than just one dataset) so that I can get an overview of that area select the one I want

* As an Awesome Curator (a member of DataHub team atm) I want to link to both datahub datasets and non-datahub datasets so that i can provide really good set of datasets to people (not everything is on the DataHub)
  * To be able to link to datahub datasets in a "shortcode way" `@core/country-list` - and this is a more fancy set of info like on publisher page (this may be for later!) so that people have more information and they can see these are datahub datasets
* I want to be able to have text as well as links so that I can add commentary or break the page into sections
* As a Visitor I want to be able to submit new links and improvements to the page so that it gets better and my stuff is on it
* As an Awesome Curator I want to review submissions prior to them going live so that I can include them

## Acceptance criteria

* [x] I can find "awesome" link in the navbar
* [x] Once I'm on the "awesome" page, I can see list of available themes
* [x] I can explore more about each theme page

## Tasks

* [x] create separate repo for `awesome` page contents, e.g., at `datahubio/awesome` [5m]
  * see structure of the repo below
  * [x] someone is watching that repo (Dima, Meiran)
* [x] implement `/awesome` route in the frontend repo so that it pulls (http) the awesome page from `awesome` repo [2h]
  * [x] it is in markdown so convert to HTML and render
    * [x] we can reuse a lot of `/docs` page - https://github.com/datahq/frontend/blob/master/routes/index.js#L220-L255 - it allows us to parse front-matter and process markdown in our way
  * [x] Support `/awesome/football` - this should point to `football.md` in the awesome repo
* [x] Add a link to "awesome" page in the navbar [5m]
* Edit / add info for curators
  * They can go directly to github and edit the text
* [ ] Edit / add info for visitors [30m]
  * [ ] "Improve this list" ("Add to this list") => link to GitHub where the current page can be edited
    * In future may want to have a popup with some instructions so the context switch does not throw people e.g. "You'll be able to edit the source of this page on github". For now not needed as i think the kind of people editing this page are familiar with the "edit on github" approach
  * This is then reviewed in the pull request
* Caching: none for now ... (avoid the complexity)

## Analysis

Structure for the new `awesome` repo:

```
/index.md   => /awesome
/README.md => not shown - just for the git repo instructions
/football.md => /awesome/football
/theme2.md
/theme3.md
```

Structure of an awesome page:

```
title:  The Best Football Datasets
description: // goes into the meta tag (this is the for future)
```

Questions:

* any support for shortcodes e.g. `@core/airport-codes` - NOT FOR NOW

**Comment by AcckiyGerman** [comment]
Tasks for @acckiygerman:
* [x] create /awesome repo
* [ ] create the awesome index page (blueprint).  30-40m
* [ ] Discuss the themes structure (it should be easy to extend awesome themes with new subtopics and pages) with @anuveyatsu   10m
(ask Anu to create route to awesome page)
* [ ] initiate an awesome theme (football) , put in git, add links to index, check it is accessible for the site visitors 1-1.5h

**Comment by AcckiyGerman** [comment]
On a review https://github.com/datahq/frontend/pull/149

**Comment by zelima** [comment]
FIXED http://datahub.io/awesome

**Comment by rufuspollock** [comment]
@zelima this was closed without ticking any checkboxes and without much detail. Please ping the issue owners if you need them to close it.
