### ISSUE TITLE
Machine Learning Datasets - Part I

### ISSUE THREAD

**Issue by rufuspollock** [datahubio/datahub-v2-pm#88]
*One large potential user group for DataHub are people working in data science and machine learning*

*Question: is there a difference between machine learning and data science? Is ML only about neural net stuff or does it include classic predictive analytics ranging from regression to random forests. My sense is that we can go with ML even what we are talking about is a bit broader.*

As someone starting learning data science (and machine learning) I want good ready-to-use sample datasets I can use for practice so that I can focus on practising analytics rather than data wrangling

* Start with simpler statistical stuff: even a regression, then classification and clustering etc
* I want to be able to import them into my tool (what is usual tool? pandas? weka?) 

As a more advanced student of machine learning I want to get a wide range of well-prepared datasets (including well known ones) that I can practise on so that I can improve and focus my efforts on learning not data acquisition

As a Machine Learning practitioner I want to find up to date datasets which I can use for implementing newest classificators so that I can contribute to machine learning community or create projects for company I work in.

*Please add to these*

## Acceptance criteria

* [x] Awesome includes a machine learning section with a brief intro text about what machine learning is and links to some good existing sources
* [x] 5+ datasets under @machine-learning user that are suitable for beginners
* [x] Next 15-20 datasets identified
* [x] Awesome section links to machine learning datasets on datahub and machine learning user
* [ ] Written up learning about experience wrangling these

## Tasks

* [x] Start by adding existing sources of data into awesome (this is good practice and useful going forwards)
  * [ ] Come up with some options for structuring DS/ML material long
* [x] Get a list of 5-10 datasets to start with
  * I'd focus on pulling from one existing source as it should have a standard data structure that means you can automate conversion to data packages
  * I think OpenML might be a good start of the UCI site
* [x] Convert the first dataset and get an estimate of time
  * [ ] ? post to reddit in datsets section (need to frame this appropriately - emphasize as a data package)
* [x] Covert the next four datasets
* [ ] Write a short blog post

## Analysis

* Connection with the OpenML folks (open machine learning): https://github.com/datahubio/qa/issues/33. We already know them so we can use this both in asking what to get and in sharing what we produce.
* May want to look into an ARFF to tabular data package conversion

**Comment by svetozarstojkovic** [comment]
First dataset that will be put into datahub is:
https://archive.ics.uci.edu/ml/datasets/seismic-bumps

**Comment by rufuspollock** [comment]
@svetozarstojkovic could you give a brief reason so that people know why (esp as we suggested going with openml by default :wink: - i'm very happy you went with this but just say why helps others who might work on this)

**Comment by svetozarstojkovic** [comment]
Next dataset to curate will be this one:
https://archive.ics.uci.edu/ml/datasets/adult

**Comment by svetozarstojkovic** [comment]
Next dataset to curate:
https://archive.ics.uci.edu/ml/datasets/Fertility

**Comment by svetozarstojkovic** [comment]
Next dataset to curate:
https://www.openml.org/d/13

**Comment by svetozarstojkovic** [comment]
Next dataset to curate: 
https://www.openml.org/d/171

**Comment by svetozarstojkovic** [comment]
Next dataset to curate: 
https://www.openml.org/d/35

**Comment by svetozarstojkovic** [comment]
Next dataset to curate:
https://www.openml.org/d/55

**Comment by svetozarstojkovic** [comment]
Next dataset to curate:
https://www.openml.org/d/945

**Comment by zelima** [comment]
@rufuspollock anything remaining on this except blog post, can we close?
@Mikanebu can you take on blog post?

**Comment by Mikanebu** [comment]
@zelima ok

**Comment by zelima** [comment]
@Mikanebu any progress here?

**Comment by Mikanebu** [comment]
@zelima I have not started yet writing blog post. I will add it in my next24

**Comment by rufuspollock** [comment]
Is this now a DUPLICATE of https://github.com/datahq/datahub-qa/issues/33?

**Comment by zelima** [comment]
FIXED/DUPLICATE. Think as a Part I this is done. The blog post will come with Part II if such will be needed. As a part of this issue, we've got the post about arrf here https://datahub.io/blog/attribute-relation-file-format-arff
